apiVersion: skaffold/v4beta7
kind: Config
profiles:
  - name: test
    manifests:
      helm:
        releases:
          - name: test
            chartPath: ./helm
            createNamespace: true
            namespace: test
            wait: true
